language: node_js

node_js: "12.16.1"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run test --coverage

after_success:
  # - codecov
  - bash <(curl -s https://codecov.io/bash) 

branches:
  only:
    - master
env:
  - CODECOV_TOKEN="0f0b771d-2cb6-47f4-99ae-a16d33024e73"
  